version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: persistence-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php-fpm:
    build: docker/php-fpm
    container_name: persistence-php
    working_dir: /application
    volumes:
      - .:/application

  memcahed:
    image: memcached:latest
    ports:
        - "11211:11211"
    container_name: persistence-memcached
    working_dir: /application
    volumes:
      - .:/application

